CREATE TABLE itmanager_trades (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL
);

CREATE TABLE itmanager_roles (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title TEXT NOT NULL
);

CREATE TABLE itmanager_workstations (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  host_name TEXT NOT NULL,
  os TEXT NOT NULL,
  version TEXT NOT NULL,
  memory INT NOT NULL,
  free_space INT NOT NULL,
  hotfix_id TEXT[] NOT NULL,
  hotfix_info TEXT[] NOT NULL,
  hotfix_date DATE[] NOT NULL 
);

CREATE TABLE itmanager_users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    email TEXT NOT NULL,
    trade_id INTEGER
        REFERENCES itmanager_trades(id) ON DELETE CASCADE NOT NULL,
    role_id INTEGER
        REFERENCES itmanager_roles(id) ON DELETE CASCADE NOT NULL,
    workstation_id INTEGER
        REFERENCES itmanager_workstations(id) ON DELETE CASCADE NOT NULL
);
