CREATE TABLE itmanager_tasks (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER 
        REFERENCES itmanager_users(id) ON DELETE CASCADE NOT NULL,
    task_details TEXT NOT NULL,
    status_code INT NOT NULL,
    due_date DATE NOT NULL
);